# Generated by Django 3.2.16 on 2023-02-01 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnvInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('env_name', models.CharField(max_length=40, unique=True)),
                ('http_url', models.CharField(max_length=40, verbose_name='http url')),
                ('ws_url', models.CharField(max_length=40, verbose_name='websocket url')),
                ('conversationId', models.CharField(max_length=50, verbose_name='话题id')),
                ('groupId', models.CharField(max_length=50, verbose_name='组id')),
                ('testPhone', models.TextField(max_length=10000, verbose_name='测试账号')),
                ('simple_desc', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '环境管理',
                'db_table': 'EnvInfo',
            },
        ),
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project_name', models.CharField(max_length=50, unique=True, verbose_name='项目名称')),
                ('simple_desc', models.CharField(max_length=100, null=True, verbose_name='简要描述')),
            ],
            options={
                'verbose_name': '项目信息',
                'db_table': 'ProjectInfo',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('status', models.IntegerField(default=1, verbose_name='用户状态')),
            ],
            options={
                'verbose_name': '用户信息',
                'db_table': 'UserInfo',
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.CharField(max_length=20, verbose_name='版本号')),
                ('simple_desc', models.CharField(max_length=50, null=True, verbose_name='版本描述信息')),
                ('project_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Imoocmapi.projectinfo', verbose_name='项目')),
            ],
            options={
                'verbose_name': '版本信息',
                'db_table': 'Version',
            },
        ),
        migrations.CreateModel(
            name='ModuleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('module_name', models.CharField(max_length=50, verbose_name='模块名称')),
                ('simple_desc', models.CharField(max_length=100, null=True, verbose_name='简要描述')),
                ('belong_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Imoocmapi.projectinfo')),
            ],
            options={
                'verbose_name': '模块信息',
                'db_table': 'ModuleInfo',
            },
        ),
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('start', models.CharField(choices=[('1', '1星'), ('2', '2星'), ('3', '3星'), ('4', '4星')], max_length=12, verbose_name='几星')),
                ('bug_title', models.CharField(max_length=500, verbose_name='bug描述')),
                ('bug_content', models.CharField(max_length=1000, verbose_name='bug详情')),
                ('platform', models.CharField(choices=[('1', 'ios'), ('2', 'android'), ('3', 'web'), ('4', 'pc'), ('5', 'pad')], max_length=12, verbose_name='bug所属平台')),
                ('state', models.CharField(choices=[('1', '未解决'), ('2', '已解决'), ('3', '延期解决'), ('4', '不解决'), ('5', '关闭')], max_length=12, verbose_name='bug状态')),
                ('pic', models.ImageField(blank=True, upload_to='images/bug', verbose_name='bug图片')),
                ('push', models.BooleanField(choices=[(False, '推送'), (True, '不推送')], verbose_name='是否推送')),
                ('buger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buger', to='Imoocmapi.userinfo', verbose_name='创建者')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developer', to='Imoocmapi.userinfo', verbose_name='开发人员')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Imoocmapi.moduleinfo', verbose_name='模块')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Imoocmapi.projectinfo', verbose_name='项目')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Imoocmapi.version', verbose_name='版本')),
            ],
            options={
                'verbose_name': 'bug',
                'db_table': 'Bug',
            },
        ),
    ]
