# Generated by Django 3.2.16 on 2023-02-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Imoocmapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='png',
            field=models.CharField(max_length=200, null=True, verbose_name='图片地址'),
        ),
    ]
