# Generated by Django 4.1.4 on 2022-12-27 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Imoocmapi', '0002_auto_20221225_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfo',
            name='version',
            field=models.ForeignKey(default='1.0', on_delete=django.db.models.deletion.CASCADE, to='Imoocmapi.version', verbose_name='版本'),
        ),
    ]
