# Generated by Django 3.2 on 2022-12-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Imoocmapi', '0003_alter_projectinfo_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('env_name', models.CharField(max_length=40, unique=True)),
                ('http_url', models.CharField(max_length=40, verbose_name='http url')),
                ('ws_url', models.CharField(max_length=40, verbose_name='websocket url')),
                ('conversationId', models.CharField(max_length=50, verbose_name='话题id')),
                ('groupId', models.CharField(max_length=50, verbose_name='组id')),
                ('testPhone', models.TextField(max_length=10000, verbose_name='测试账号')),
                ('simple_desc', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '环境管理',
                'db_table': 'EnvInfo',
            },
        ),
    ]
