# Generated by Django 3.2 on 2022-12-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Imoocmapi', '0004_envinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='simple_desc',
            field=models.CharField(max_length=50, null=True, verbose_name='版本描述信息'),
        ),
    ]
